package noc

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	NocRouter
	NocPriorityRouter
	NocReasonsRouter
	NocDepartmentRouter
	NocStatusRouter
	NocTeamRouter
	NocDirectReasonsRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
